name: Go build and deploy

on:
  push:
    branches: [ main, master ]

env:
  IMAGE_NAME: "auth-service"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_HOST }}

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag ${{ REGISTRY_HOST }}/${{ secrets.REGISTRY_NAME }}/$IMAGE_NAME:$TAG_NAME -f ./server.Dockerfile . --provenance=false