name: Go lint and test

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.5
        with:
          go-version: '1.24.3'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=30m --config=./.golangci.pipeline.yaml
      - name: Test
        run: go test -v ./...